name: Sven
favicon: null
layout_spectrum: 0.35881
typography_spectrum: 0.31224
title: Comme un ruisseau
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070b17'
    - '#354d7d'
    - '#e6f8fc'
    - '#89a4cf'
    - '#de4f3e'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
